**UNICEF Dashboard**
* get dataset
* clean it to get necessary data
* create different dataframes for each category
* created from 15, March 2023

In [77]:
#import important libraries
import pandas as pd
import plotly.express as px
import numpy as np

In [78]:
df_sdg=pd.read_excel(r'C:\Users\ENVY\Desktop\Data science\SDG DATA_UNICEF.xlsx')

In [79]:
df_sdg

,Indicator,Series,Series_Code,Composite,Unit_Code,Occupation,Occupation_Code,Ref_Area,Province,District,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1.1.1,Proportion of population below the internation...,SI_POV_DAY1,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,56.8,NaN,NaN,55.5,NaN,NaN,NaN,NaN,NaN
1,1.2.1,Proportion of population living below the nati...,SI_POV_NAHC,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,39.1,NaN,NaN,38.2,NaN,NaN,NaN,NaN
2,1.2.1,Proportion of population living below the nati...,SI_POV_NAHC,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,33.2,NaN,NaN,31.6,NaN,NaN,NaN,NaN
3,1.2.1,Proportion of population living below the nati...,SI_POV_NAHC,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,35.9,NaN,NaN,34.8,NaN,NaN,NaN,NaN
4,1.2.1,Proportion of population living below the nati...,SI_POV_NAHC,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,44.7,NaN,NaN,44.2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,8.7.1,Proportion and number of children aged 5‑17 ye...,SL_TLF_CHLDEA,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,6.4,NaN,NaN,4.0,NaN,NaN,NaN,NaN
169,8.7.1,Proportion and number of children aged 5‑17 ye...,SL_TLF_CHLDEA,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,4.7,NaN,NaN,3.2,NaN,NaN,NaN,NaN
170,16.9.1,Proportion of children under 5 years of age wh...,SG_REG_BRTH,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,NaN,56.0,NaN,NaN,NaN,NaN,85.6,NaN
171,16.9.1,Proportion of children under 5 years of age wh...,SG_REG_BRTH,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.8,NaN
172,16.9.1,Proportion of children under 5 years of age wh...,SG_REG_BRTH,_T,PT,NaN,_T,RW,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.4,NaN

In [81]:
df_sdg=df_sdg.drop(columns=['Series_Code','Composite','Occupation','Occupation_Code','Urbanization_Code','Education_Code','Sex_Code','Seats','Age_Code'])

In [83]:
df_child_poverty=df_sdg[df_sdg['Age']=='<15']
df_child_poverty

,Indicator,Series,Unit_Code,Ref_Area,Province,District,Urbanization,Education,Data Source,Description,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
4,1.2.1,Proportion of population living below the nati...,PT,RW,NaN,NaN,NaN,NaN,"EICV, NISR",Proportion of population living below the nati...,...,NaN,NaN,44.7,NaN,NaN,44.2,NaN,NaN,NaN,NaN
5,1.2.1,Proportion of population living below the nati...,PT,RW,NaN,NaN,NaN,NaN,"EICV, NISR",Proportion of population living below the nati...,...,NaN,NaN,44.6,NaN,NaN,44.8,NaN,NaN,NaN,NaN

In [84]:
df_child_poverty=df_child_poverty.drop(columns=['Unit_Code','Ref_Area','Province','District','Urbanization','Education ',2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013])

In [86]:
df_child_poverty=df_child_poverty[['Sex',2014,2015,2016,2017,2018,2019,2020,2021]]
#df_child_poverty

<h3> Transpose the data</h3>

  Transform the rows into columns using T as transpose keywords

In [87]:
df_child_poverty=df_child_poverty.T

In [89]:
#convert the first row as column head

df_child_poverty.columns=df_child_poverty.iloc[0]

In [90]:
#remove the first row due to duplication
df_child_poverty=df_child_poverty[1:]

**Fill in the missing values for all numeric columns using forward fill**
* this is because the data still valid until new survey is conducted
> the forward fill has logic

In [91]:
df_child_poverty['Male']=df_child_poverty['Male'].fillna(method='ffill')
df_child_poverty['Female']=df_child_poverty['Female'].fillna(method='ffill')
df_child_poverty=df_child_poverty.reset_index()
df_child_poverty=df_child_poverty.melt(id_vars='index')
#df_child_poverty

C:\Users\ENVY\AppData\Local\Temp\ipykernel_5616\3178394967.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_child_poverty['Male']=df_child_poverty['Male'].fillna(method='ffill')
C:\Users\ENVY\AppData\Local\Temp\ipykernel_5616\3178394967.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_child_poverty['Female']=df_child_poverty['Female'].fillna(method='ffill')

In [92]:
df_child_poverty.to_csv('children_poverty.csv')

<h1>Malnutrition Part: Source : DHS (Demographic and Health Survey) </h1>

In [93]:
''' selecting malnutrition in the series and stunting to get data of malnourished children '''

df_malnutr=df_sdg[df_sdg['Series'].str.contains('malnutrition') | df_sdg['Series'].str.contains('stunting')]

In [95]:
df_malnutr=df_malnutr.drop(columns=['Unit_Code','Ref_Area','Province','District','Urbanization','Education ',2000,2001,2002,2003,2004])

In [97]:
#transpose the dataset

df_malnutr=df_malnutr.T
#df_malnutr

In [98]:
#reduce the columns and select the column names

df_malnutr.columns=df_malnutr.iloc[3]
df_malnutr=df_malnutr[5:]
#df_malnutr

In [99]:
''' selecting malnutrition in the series and stunting to get data of malnourished children '''

df_malnutr=df_sdg[df_sdg['Series'].str.contains('malnutrition') | df_sdg['Series'].str.contains('stunting')]

#drop some unimportant columns

df_malnutr=df_malnutr.drop(columns=['Unit_Code','Ref_Area','Province','District','Urbanization','Education ',2000,2001,2002,2003,2004])

#transpose the dataset

df_malnutr=df_malnutr.T

#reduce the columns and select the column names

df_malnutr.columns=df_malnutr.iloc[3]
df_malnutr=df_malnutr[5:]

#stunted,wasted and overweight malnutrition types
#stunting
'''
here, we are going to make three different datasets for each malnutrition type

1. stunting : height by age

2. wasting : weight for height

3. overweight:


'''
#stunting

df_malnutr_stunted=df_malnutr['Proportion of children moderately or severely stunted']

df_malnutr_stunted.columns=df_malnutr_stunted.iloc[0]
df_malnutr_stunted=df_malnutr_stunted[1:]
df_malnutr_stunted=df_malnutr_stunted.fillna(method='ffill')
df_malnutr_stunted['indicator']='stunting'
#print(df_malnutr_stunted)

#wasting

df_malnutr_wasting=df_malnutr['Proportion of children moderately or severely wasted']
df_malnutr_wasting.columns=df_malnutr_wasting.iloc[0]
df_malnutr_wasting=df_malnutr_wasting[1:]
df_malnutr_wasting=df_malnutr_wasting.fillna(method='ffill')
df_malnutr_wasting['indicator']='wasting'
#print(df_malnutr_wasting)

#overweight

df_malnutr_overweight=df_malnutr['Proportion of children moderately or severely overweight']
df_malnutr_overweight.columns=df_malnutr_overweight.iloc[0]
df_malnutr_overweight=df_malnutr_overweight[6:]
df_malnutr_overweight=df_malnutr_overweight.fillna(method='ffill')
df_malnutr_overweight['indicator']='overweight'
#print(df_malnutr_overweight)
#combines all the sub datasets to make malnutrition dataset
malnutrition=pd.concat([df_malnutr_stunted,df_malnutr_wasting,df_malnutr_overweight])
#malnutrition

In [100]:
malnutrition.to_csv('mal_dataset.csv')

<h1>Health: Source: DHS (Demographic and Health Survey)</h1>

In [101]:
''' 
selecting health data from the dataset

1. Proportion of births attended by skilled health personnel
2. Under-five mortality rate
3. Neonatal mortality rate

'''
#get health children related data
df_health=df_sdg[df_sdg['Series'].str.contains('births attended by skilled health personnel') | df_sdg['Series'].str.contains('Under-five') | df_sdg['Series'].str.contains('Neonatal') | df_sdg['Series'].str.contains('new HIV')]

#drop unimportant columns
df_health=df_health.drop(columns=['Unit_Code','Ref_Area','Data Source','Education ','District','Description','Age'])
#transpose the dataset
df_health=df_health.T

#changing the columns headers of dataset
df_health.columns=df_health.iloc[1]
df_health=df_health[2:]

# 1. Proportion of births attended by skilled health personnel

df_health_birth_attended_skilled=df_health['Proportion of births attended by skilled health personnel']

#remove sex row from the dataset as it has no value in Proportion of births attended by skilled health personnel
df_health_birth_attended_skilled=df_health_birth_attended_skilled.drop(index='Sex')

#select data related to residence for Proportion of births attended by skilled health personnel

'''
for this task, we select all rows and consider only the first four columns
which includes information on residence
we fill forward because data is updated when new survey results is out

source: DHS (Demographic and Health Survey)
'''
df_health_birth_attended_res=df_health_birth_attended_skilled.iloc[::,:3]
df_health_birth_attended_res=df_health_birth_attended_res.drop(index='Province')
df_health_birth_attended_res.columns=df_health_birth_attended_res.iloc[0]
df_health_birth_attended_res=df_health_birth_attended_res[1:]
df_health_birth_attended_res=df_health_birth_attended_res.fillna(method='ffill')
df_health_birth_attended_res=df_health_birth_attended_res.dropna(axis = 0, how ='all')
df_health_birth_attended_res = df_health_birth_attended_res.reset_index()
df_health_birth_attended_res=df_health_birth_attended_res.melt(id_vars='index')
#df_health_birth_attended_res

#select data related to provinces

'''
for this task, we select all rows and consider only the columns where there is province data
we delete data related to location

we make the provinces column as the header 
we do fill forward method to replace null values
rows with null values are dropped out

'''
df_health_birth_attended_res=df_health_birth_attended_skilled.iloc[::,:3]
df_health_birth_attended_res=df_health_birth_attended_res.drop(index='Province')
df_health_birth_attended_res.columns=df_health_birth_attended_res.iloc[0]
df_health_birth_attended_res=df_health_birth_attended_res[1:]
df_health_birth_attended_res=df_health_birth_attended_res.fillna(method='ffill')
df_health_birth_attended_res=df_health_birth_attended_res.dropna(axis = 0, how ='all')
df_health_birth_attended_res = df_health_birth_attended_res.reset_index()
df_health_birth_attended_res=df_health_birth_attended_res.melt(id_vars='index')
#df_health_birth_attended_res


#2. Under five mortality rate
'''
create dataframe contained underfive mortality data
remove unimportant columns
do manipulations: fill forward, transpose rows and columns
'''
df_health_underfive=df_sdg[df_sdg['Series']=='Under_five mortality rate']
df_health_underfive=df_health_underfive.drop(columns=['Unit_Code','Ref_Area','Education ','Data Source','Description','Indicator','Age'])
df_health_underfive=df_health_underfive.T

#create table under five mortality rate (per 1000) by provinces
#remove unimportant columns 
df_health_underfive.columns=df_health_underfive.iloc[1]
df_health_underfive_province=df_health_underfive[3:]
df_health_underfive_province=df_health_underfive_province.drop(index=['Urbanization','Sex'])
df_health_underfive_province=df_health_underfive_province.iloc[::,5:]
df_health_underfive_province=df_health_underfive_province.fillna(method='ffill')
df_health_underfive_province=df_health_underfive_province.dropna()
df_health_underfive_province=df_health_underfive_province.reset_index()
df_health_underfive_province=df_health_underfive_province.melt(id_vars='index')
#df_health_underfive_province

#create a table of underfive mortality by residence

df_health_underfive.columns=df_health_underfive.iloc[3]
df_health_underfive_res=df_health_underfive.iloc[::,:5]
df_health_underfive_res=df_health_underfive_res.drop(index=['Series','Province','District','Urbanization','Sex'])
df_health_underfive_res=df_health_underfive_res[['Urban','Rural']]
df_health_underfive_res=df_health_underfive_res.fillna(method='ffill')
df_health_underfive_res=df_health_underfive_res.dropna()
df_health_underfive_res=df_health_underfive_res.reset_index()
df_health_underfive_res=df_health_underfive_res.melt(id_vars='index')
#df_health_underfive_res

#create a table of underfive mortality by sex

df_health_underfive.columns=df_health_underfive.iloc[4]
df_health_underfive_sex=df_health_underfive.iloc[::,:3]
df_health_underfive_sex=df_health_underfive_sex.drop(index=['Series','Province','District','Urbanization','Sex'])
df_health_underfive_sex=df_health_underfive_sex.fillna(method='ffill')
df_health_underfive_sex=df_health_underfive_sex.dropna(axis=0,how='all')
df_health_underfive_sex=df_health_underfive_sex.reset_index()
df_health_underfive_sex=df_health_underfive_sex.melt(id_vars='index')
#df_health_underfive_sex

#3. Neonatal mortality rate (per 1000 live birth)
df_health_neonatal=df_health['Neonatal mortality rate']
df_health_neonatal.columns=df_health_neonatal.iloc[1]
df_health_neonatal_res=df_health_neonatal.iloc[::,:3]
df_health_neonatal_res=df_health_neonatal_res.drop(index=['Province','Urbanization','Sex'])
df_health_neonatal_res=df_health_neonatal_res.fillna(method='ffill')
df_health_neonatal_res=df_health_neonatal_res.dropna(axis=0,how='all')
df_health_neonatal_res=df_health_neonatal_res.reset_index()
df_health_neonatal_res=df_health_neonatal_res.melt(id_vars='index')
#df_health_neonatal_res

#Neonatal mortality rate by sex
#Neonatal mortality rate by sex
df_health_neonatal.columns=df_health_neonatal.iloc[2]
df_health_neonatal_sex=df_health_neonatal.iloc[::,3:]
df_health_neonatal_sex=df_health_neonatal_sex.drop(index=['Province','Urbanization','Sex'])
df_health_neonatal_sex=df_health_neonatal_sex.fillna(method='ffill')
df_health_neonatal_sex=df_health_neonatal_sex.dropna(axis=0,how='all')
df_health_neonatal_sex=df_health_neonatal_sex.reset_index()
df_health_neonatal_sex=df_health_neonatal_sex.melt(id_vars='index')
#df_health_neonatal_sex

#Adolescent birth rate by residence

df_health_adolescent_res=df_sdg[df_sdg['Series'].str.contains('Adolescent')]
df_health_adolescent_res=df_health_adolescent_res.drop(columns=['Indicator','Unit_Code','Ref_Area','Province','District','Education ','Data Source'])
df_health_adolescent_res=df_health_adolescent_res.T
df_health_adolescent_res.columns=df_health_adolescent_res.iloc[1]
df_health_adolescent_res=df_health_adolescent_res.drop(index=['Series','Urbanization','Description','Age','Sex'])
df_health_adolescent_res=df_health_adolescent_res.fillna(method='ffill')
df_health_adolescent_res=df_health_adolescent_res.dropna(axis=0,how='all')
df_health_adolescent_res=df_health_adolescent_res.reset_index()
df_health_adolescent_res=df_health_adolescent_res.melt(id_vars=['index'])
# df_health_adolescent_res

#df_health_adolescent_res

#vaccine DPT3, MCV2

df_health_vaccine_sex = df_sdg[df_sdg['Description'].str.contains('diphtheria-tetanus') | df_sdg['Description'].str.contains('vaccine second-dose')]
df_health_vaccine_sex = df_health_vaccine_sex.drop(columns=['Indicator','Series','Unit_Code','Ref_Area','Province','District','Urbanization','Education ','Data Source'])
df_health_vaccine_sex = df_health_vaccine_sex.T
df_health_vaccine_sex.columns = df_health_vaccine_sex.iloc[0]
df_health_vaccine_sex=df_health_vaccine_sex.drop(index=['Description','Age'])
df_health_vaccine_sex.columns=df_health_vaccine_sex.iloc[0]
df_health_vaccine_sex=df_health_vaccine_sex[1:]

#creaating table for DTP3
df_health_vaccine_sex_DTP3 = df_health_vaccine_sex.iloc[::,:3]

#forward fill
df_health_vaccine_sex_DTP3=df_health_vaccine_sex_DTP3.fillna(method='ffill')

#delete rows whose all values are null
df_health_vaccine_sex_DTP3 = df_health_vaccine_sex_DTP3.dropna(axis=0,how='all')
df_health_vaccine_sex_DTP3['indicator'] = 'DTP3'
#df_health_vaccine_sex_DTP3

#create tables for MCV2

df_health_vaccine_sex_MCV2 = df_health_vaccine_sex.iloc[::,3:]

#forward fill
df_health_vaccine_sex_MCV2 = df_health_vaccine_sex_MCV2.fillna(method='ffill')
#delete rows whose all values are null
df_health_vaccine_sex_MCV2 = df_health_vaccine_sex_MCV2.dropna(axis=0,how='all')
df_health_vaccine_sex_MCV2['indicator'] = 'MCV2'

df_health_vaccine=pd.concat([df_health_vaccine_sex_DTP3,df_health_vaccine_sex_MCV2])
#df_health_vaccine

**Child Protection**
* Labor
* Registration
* any form of Violence (physical, sexual) 
* birth registration 
* Source: EICV, DHS

In [102]:
#select data for child protection

df_protection=df_sdg[df_sdg['Series'].str.contains('sexual') | df_sdg['Series'].str.contains('were married or in a union') | df_sdg['Series'].str.contains('child labour') | df_sdg['Series'].str.contains('civil authority')]
df_protection=df_protection.drop(columns=['Indicator','Unit_Code','Ref_Area','Province','District','Urbanization','Education ','Data Source'])
df_protection=df_protection.T
df_protection.columns=df_protection.iloc[1]
df_protection=df_protection.drop(index=['Series','Description','Age'])

#Physical violence
df_protection_physical=df_protection.iloc[::,:1]
df_protection_physical.columns=df_protection_physical.iloc[0]
#df_protection_physical=df_protection_physical.fillna(method='ffill')
df_protection_physical=df_protection_physical.iloc[1:]
df_protection_physical=df_protection_physical.fillna(method='ffill')
df_protection_physical=df_protection_physical.dropna()
df_protection_physical['indicator'] = 'women and girls subjected to physical violence by a current or former intimate partner in the previous 12 months'
#df_protection_physical


#sexual violence

df_protection_sexual=df_protection.iloc[::,1:2]
df_protection_sexual.columns=df_protection_sexual.iloc[0]
df_protection_sexual=df_protection_sexual.iloc[1:]
df_protection_sexual=df_protection_sexual.fillna(method='ffill')
df_protection_sexual=df_protection_sexual.dropna()
df_protection_sexual['indicator'] = 'women and girls subjected to sexual violence by a current or former intimate partner in the previous 12 months'


#pyschological violence

#psychological violence
df_protection_psychological=df_protection.iloc[::,2:3]
df_protection_psychological.columns=df_protection_psychological.iloc[0]
df_protection_psychological=df_protection_psychological.iloc[1:]
df_protection_psychological=df_protection_psychological.fillna(method='ffill')
df_protection_psychological=df_protection_psychological.dropna()
df_protection_psychological['indicator'] = 'women and girls subjected to psychological violence by a current or former intimate partner in the previous 12 months'

#15 years and older subjected to sexual violence by persons other than an intimate partner in the previous 12 months
df_protection_sexual_others = df_protection.iloc[::,3:4]
df_protection_sexual_others.columns = df_protection_sexual_others.iloc[0]
df_protection_sexual_others = df_protection_sexual_others.iloc[1:]
df_protection_sexual_others = df_protection_sexual_others.fillna(method='ffill')
df_protection_sexual_others = df_protection_sexual_others.dropna()
df_protection_sexual_others['indicator'] = 'women and girls aged 15 years and older subjected to sexual violence by persons other than an intimate partner in the previous 12 months'

# Proportion of women aged 20-24 years who were married or in a union before age 15

df_protection_union_15 = df_protection.iloc[::,4:5]
df_protection_union_15.columns = df_protection_union_15.iloc[0]
df_protection_union_15 = df_protection_union_15.iloc[1:]
df_protection_union_15 = df_protection_union_15.fillna(method='ffill')
df_protection_union_15 = df_protection_union_15.dropna()
df_protection_union_15['indicator'] = 'women aged 20-24 years who were married or in a union before age 15'

# Proportion of women aged 20-24 years who were married or in a union before age 18

df_protection_union_18 = df_protection.iloc[::,5:6]
df_protection_union_18.columns = df_protection_union_18.iloc[0]
df_protection_union_18 = df_protection_union_18.iloc[1:]
df_protection_union_18 = df_protection_union_18.fillna(method='ffill')
df_protection_union_18 = df_protection_union_18.dropna()
df_protection_union_18['indicator'] = 'women aged 20-24 years who were married or in a union before age 18'

#concatenating all the dataframes to get single dataframes related to female violence

df_protection_female_violence=pd.concat([df_protection_physical,df_protection_sexual,df_protection_union_15,df_protection_union_18])
df_protection_female_violence

#Proportion of children engaged in economic activity

df_protection_labor = df_protection.iloc[::,6:9]
df_protection_labor.columns = df_protection_labor.iloc[0]
df_protection_labor = df_protection_labor.iloc[1:]
df_protection_labor = df_protection_labor.fillna(method='ffill')
df_protection_labor = df_protection_labor.dropna(axis=0,how='all')
df_protection_labor=df_protection_labor.reset_index()
df_protection_labor=df_protection_labor.melt(id_vars='index')
#df_protection_labor


#Proportion of children under 5 years of age whose births have been registered with a civil authority

df_protection_registration = df_protection.iloc[::,9:12]
df_protection_registration.columns = df_protection_registration.iloc[0]
df_protection_registration = df_protection_registration.iloc[1:]
df_protection_registration = df_protection_registration.fillna(method='ffill')
df_protection_registration = df_protection_registration.dropna(axis=0,how='all')
df_protection_registration=df_protection_registration.reset_index()
df_protection_labor=df_protection_registration.melt(id_vars='index')
#df_protection_registration

<h1> Environment</h1>

**Proportion of population using safely managed drinking water services**

**Proportion of population using safely managed sanitation services**
  * Getting data into Jupter 
  * Filtering data related to environment
  * Cleaning the data
  * save the data into different tables

In [103]:
'''
Getting the data.
remove an unimportant documents
'''

df_environment = df_sdg[df_sdg['Series'].str.contains('drinking water services') | df_sdg['Series'].str.contains('managed sanitation services')]
df_environment = df_environment.drop(columns=['Indicator','Unit_Code','Ref_Area','Province','District','Urbanization','Education ','Data Source','Age','Sex'])

'''
Selecting indicators relating to drinking water
'''
df_environment_drink_water = df_environment[df_environment['Series'].str.contains('drinking water services')] 
df_environment_drink_water = df_environment_drink_water.T #transpose the data
#getting the final dataset of drinking water

df_environment_drink_water.columns = df_environment_drink_water.iloc[1]
df_environment_drink_water = df_environment_drink_water[2:]
df_environment_drink_water = df_environment_drink_water.fillna(method='ffill')
df_environment_drink_water = df_environment_drink_water.dropna(axis=0, how='all')
df_environment_drink_water = df_environment_drink_water.reset_index()
df_environment_drink_water = df_environment_drink_water.melt(id_vars=['index'])
#df_environment_drink_water

'''
selecting indicators related to safely managed sanitation services

'''
df_environment_sanitation = df_environment[df_environment['Series'].str.contains('managed sanitation services')]
df_environment_sanitation = df_environment_sanitation.T
df_environment_sanitation.columns = df_environment_sanitation.iloc[1]
df_environment_sanitation = df_environment_sanitation[2:]
df_environment_sanitation = df_environment_sanitation.fillna(method='ffill')
df_environment_sanitation = df_environment_sanitation.dropna(axis=0, how='all')
df_environment_sanitation = df_environment_sanitation.reset_index()
df_environment_sanitation = df_environment_sanitation.melt(id_vars=['index'])
#df_environment_sanitation

In [104]:
pwd

'C:\\Users\\ENVY\\PycharmProjects\\UNICEF\\EICV dash'